services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: family_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/family_search
      TESSDATA_PREFIX: /usr/share/tesseract-ocr/5/tessdata
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    # Remova a linha abaixo se não quiser hot reload
    command: [ "nginx", "-g", "daemon off;" ]

volumes:
  db_data:
